Update createNew and startExisting workout pages
UNLV-CS472-672/2024-S-GROUP3-Barbell pull request #223
Opened 2024-04-19 23:37 UTC by L-Hen

Replaced nav bar with newest version. Implemented selection to createNew exercises. Implemented functional search bar.
Cleaned up index pages.

# What type of PR is this? (Check all that apply)

- [x] ✨**feature**: Introduces completely new code or new features.
- [x] 🐛**fix**: Implements changes that fix a bug. Ideally, reference an issue if present.
- [ ] ♻️**refactor**: Includes any code-related change that is neither a fix nor a feature.
- [ ] ✅**build**: Encompasses all changes related to the build of the software, including changes to dependencies or the addition of new ones.
- [ ] ⚡️**test**: Pertains to all changes regarding tests, whether adding new tests or modifying existing ones.
- [ ] 🚰**ci**: Involves all changes related to the configuration of continuous integration, such as GitHub Actions or other CI systems.
- [ ] 📚**docs**: Includes all changes to documentation, such as README files, or any other documentation present in the repository.
- [ ] 🗑️**chore**: Captures all changes to the repository that do not fit into the above categories.

# Description

What did you change? How did you change it?
Implemented functionality to "start new exercise" page.

# Tests

How was this tested?

- [ ] Unit tests
- [ ] Integration tests
- [ ] E2E tests
- [x] Manual tests
- [ ] Tests were NOT needed
- [ ] Other (explain below)

# [Optional] Screenshots

# Documentation

- [ ] Added to README.me
- [ ] Seperate document
- [ ] NO documentation needed

Link to external documentation:

# [Optional] Are there any post-deployment tasks we need to perform?
Still need functionality
Filter by equipment (Button)
Use Diagram (Button)
Send array of exercises selected to following page.
Start Freeform Workout (Button)

2024-04-21 04:11 UTC, thienguen commented
reviewing now

2024-04-21 04:32 UTC, thienguen requested changes
yea, naw

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/createNew/index.tsx
> +import Nav from '~/app/nav'
remove unused import

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/createNew/index.tsx
> +import Nav from '~/app/nav'
also, run prettier format on this,

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/createNew/index.tsx
> +
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/7100bcdd-e219-493b-8ff5-9f38bfc9dc17)

the filter by equipment and the use diagram need to be synced.

Also we run into errors of

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/07883c59-e1db-434f-b62e-231e8990801f)

I believe Elliot pr fix this. or I could be mistaken, regardless, its an error

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/startExisting/index.tsx
>  import { router } from 'expo-router'
remove unsused import, format prettier x2

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/startExisting/index.tsx
there is a lot of questionable code in this file. :( 
we also run into the same problem of 

```
 ERROR  Warning: Each child in a list should have a unique "key" prop.
 ```

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/startExisting/index.tsx
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/5ce9182b-e688-4b39-a1e3-2795ee2d933f)

why there is 2 workout list,  

```
<View style={{height: 1, backgroundColor: '#CACACA', marginHorizontal: 13, opacity: 0.3, top: 10, }}/>
```

that view doesn't do anything.

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/components/workout/exerciseList.tsx
prettier x3

2024-04-21 04:32 UTC, thienguen commented on apps/expo/src/app/workout/createNew/index.tsx
> +
```
        <TouchableOpacity className="px-4 py-[6px] rounded-[5px] fixed border-[#CACACA] bg-[#424242]" >
            <Text className="rounded-[5px] text-[20px] text-[#FFFFFF] text-center">
              Start Freeform Workout
            </Text>
        </TouchableOpacity>
```

I can't see where this button is at all 

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/6e1680cc-8f99-4e5e-84c3-7c88277cbcaa)

2024-04-21 04:36 UTC, AaronFmyHub commented
I got a warning say add unique "Key" Prop, but a warning is a warning

2024-04-21 04:42 UTC, AaronFmyHub commented on apps/expo/src/app/workout/createNew/index.tsx
> +        <NavBar
Have less room at top
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/146596967/3832f6ec-184a-493b-9ed6-b0b7eaf68942)

2024-04-21 06:13 UTC, thienguen commented
@mva919 Please suggest your changes to the layout of this page

2024-04-21 08:18 UTC, L-Hen commented on apps/expo/src/app/workout/createNew/index.tsx
> +import Nav from '~/app/nav'
done

2024-04-22 22:46 UTC, L-Hen commented
Addressed comments, ready for re-review

2024-04-23 00:52 UTC, thienguen commented
> Addressed comments, ready for re-review

re-review by tonight

2024-04-23 05:03 UTC, thienguen commented
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/99fb19ba-bec8-4bb1-86dc-d8a239dea8d5)

2024-04-23 05:04 UTC, thienguen commented
the above was fine, 

but could have some padding so it doesn't stick to the rear too much like what you did to the other page

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/a9aeea15-de60-4448-a1d7-45c4a9d1613d)

good work implementing the taylor navbar

2024-04-23 05:06 UTC, thienguen approved these changes

2024-04-23 05:11 UTC, merged