239 frontend new select exercise based on muscle group page
UNLV-CS472-672/2024-S-GROUP3-Barbell pull request #258
Opened 2024-04-24 23:15 UTC by AaronFmyHub

# What type of PR is this? (Check all that apply)

- [x] ✨**feature**: Introduces completely new code or new features.
- [ ] 🐛**fix**: Implements changes that fix a bug. Ideally, reference an issue if present.
- [x] ♻️**refactor**: Includes any code-related change that is neither a fix nor a feature.
- [ ] ✅**build**: Encompasses all changes related to the build of the software, including changes to dependencies or the addition of new ones.
- [ ] ⚡️**test**: Pertains to all changes regarding tests, whether adding new tests or modifying existing ones.
- [ ] 🚰**ci**: Involves all changes related to the configuration of continuous integration, such as GitHub Actions or other CI systems.
- [ ] 📚**docs**: Includes all changes to documentation, such as README files, or any other documentation present in the repository.
- [ ] 🗑️**chore**: Captures all changes to the repository that do not fit into the above categories.

# Description

Created the page where user select exercise based on prior muscle selection.
This handles the issue @elliotwesoff created before about backend query, and it closes another issue #239 
This page displays exercises that match user selected muscle group from the list we provided and further lower informational searching cost for user by having user friendly UI/UX design.
The page contains select/unselect feature, and the number next to Add activates when user has a valid selection, it indicates the total exercises user selected.
It also includes a reset feature, which is useful when users are dealing with large lists.

# Tests

How was this tested?

- [ ] Unit tests
- [ ] Integration tests
- [ ] E2E tests
- [x] Manual tests
- [ ] Tests were NOT needed
- [ ] Other (explain below)

# [Optional] Screenshots
[exerciseFilter.webm](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/146596967/32f3da58-c9c8-47cb-9f01-46552db79554)

# Documentation

- [ ] Added to README.me
- [ ] Seperate document
- [x] NO documentation needed

Link to external documentation:

# [Optional] Are there any post-deployment tasks we need to perform?
We need to nav from muscleGroup to this page and pass in the passNext.

# AI Usage
ChatGPT explained Truthy/Falsy to me and helped me to find a solution display filtered content.
It also wrote the code to reset array, which contains user selections.
https://chat.openai.com/share/32926458-88e0-430c-a875-85edf02efb96

2024-04-24 23:45 UTC, StefanoRubini reviewed
Hello Aaron! Nice work for implementing the Select Exercise page. Could it be possible to add some styling to the right-hand side where it says "Add-x"? Thank you! 😃
<img width="428" alt="Screenshot 2024-04-24 at 4 44 38 PM" src="https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/124111831/3201e34f-abc1-4e98-986b-b748dc49809e">

2024-04-25 00:26 UTC, bigboidanwithacan approved these changes
Great Job on this Aaron! I checked out the branch and tested it on my end, and everything worked great!  
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/38168108/da2d4103-9642-4f46-9513-268a84c9af32)

2024-04-25 00:26 UTC, bigboidanwithacan commented on apps/expo/src/app/filteredExercises/index.tsx
> +import NavBar from '~/components/ui/nav-bar/NavBar'
Remove unused import

2024-04-29 04:59 UTC, elliotwesoff commented on apps/expo/src/app/filteredExercises/index.tsx
> +      {/*<NavBar*/}
Please remove commented code if it won't be used later

2024-04-29 04:59 UTC, elliotwesoff commented on apps/expo/src/app/filteredExercises/index.tsx
> +      {/*<View className='flex flex-row items-center'>*/}
Please remove commented code

2024-04-29 05:00 UTC, elliotwesoff commented on apps/expo/src/app/filteredExercises/index.tsx
> +              {exercise?.bodyPart == 'ARMS' && muscle == muscleSelectUser.Arm && (
From here to line 161 could be refactored into a loop, but I understand if we don't have time for that now

2024-04-29 05:01 UTC, elliotwesoff commented on apps/expo/src/app/filteredExercises/index.tsx
> +          onPress={() => {}}
Should this onPress do something?

2024-04-29 05:02 UTC, elliotwesoff approved these changes
Just double check the onPress callback for the finish button. I left a comment. Everything else LGTM.

2024-04-29 05:11 UTC, taylorfinelli commented
Isn't this supposed to filter based on the body part selected on the diagram?

2024-04-29 05:24 UTC, taylorfinelli requested changes
Needs to be connected to the 2D model page and filter workouts based on selected body part

2024-04-29 22:08 UTC, taylorfinelli commented
Updated to include functionality and minor styling changes

https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/85365584/e7b6065a-ae61-436f-b7b8-58b9eff99d5f

Ready to be linked to workout view page. Go to `apps/expo/src/app/filteredExercises/index.tsx` and change the pathname on line 33

2024-04-29 22:10 UTC, taylorfinelli approved these changes

2024-04-29 22:11 UTC, mva919 approved these changes
🪨

2024-04-29 22:12 UTC, merged